{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "tenthplanet-service.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "opto.role-arn" . }}
{{- end }}
